name: Firmware Dumper
 
on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: "Direct Link of the ROM/Firmware to Dump"
        required: true
      EXTRA_CMD:
        description: "Any Extra Command to Run Before Dump"
        required: false

defaults:
  run:
    shell: bash

env:
  # ROM
  ROM_URL: ${{ github.event.inputs.ROM_URL }}

  # Gitlab
  PUSH_TO_GITLAB: true

  # Extra Command
  EXTRA_CMD: ${{ github.event.inputs.EXTRA_CMD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkouts
         uses: actions/checkout@v2

       - name: Clone Our Firmware Dumper
         run: |
              git clone https://github.com/Android-FW-Dumps/dumper.git

       - name: Setup Our Firmware Dumper's environment
         working-directory: dumper
         run: |
              sudo bash setup.sh
              git config --global user.name "Sushrut1101"
              git config --global user.email "guptasushrut@gmail.com"

       - name: Setup Config envs
         working-directory: dumper
         run: |
              # echo "${{ secrets.GIT_TOKEN }}" > .github_token
              # echo "${{ secrets.GIT_ORG_NAME }}" > .github_orgname
              echo "${{ secrets.GITLAB_TOKEN }}" > .gitlab_token
              echo "${{ secrets.GITLAB_GROUP }}" > .gitlab_group
              echo "${{ secrets.BOT_TOKEN }}" > .tg_token
              echo "${{ secrets.CHAT_ID }}" > .tg_chat

       - name: Run the Extra Command
         working-directory: dumper
         run: |
              $EXTRA_CMD

       - name: Start Dumping
         working-directory: dumper
         run: |
              ./dumper.sh "$ROM_URL"
