name: Dump
 
on:
  push:
    branches: [ main ]

env:
  ROM_URL: https://pilotfiber.dl.sourceforge.net/project/crdroid//j7xelte/6.x/crDroidAndroid-10.0-20210125-j7xelte-v6.14.zip
  TZ: America/Sao_Paulo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkouts
         uses: actions/checkout@v2

       - name: Setup Dump Environment
         run: |
              sudo apt install unace unrar zip unzip p7zip-full p7zip-rar sharutils rar uudeview mpack arj cabextract device-tree-compiler liblzma-dev python3-pip python3-setuptools brotli liblz4-tool axel gawk aria2 detox cpio rename
              pip3 install pip setuptools wheel -U
              pip3 install backports.lzma protobuf pycrypto docopt zstandard twrpdtgen

       - name: Running Dumpyara Shell Script
         run: |
              bash .github/workflows/dumpyara.sh "$ROM_URL"

       - name: Checking Folder
         run: |
              cd /home/runner/work/AndroidDumpsCI/AndroidDumpsCI/.github/workflows/working/
              ls -la

       - name: Compressing with tar.xz
         run: |
              cd /home/runner/work/AndroidDumpsCI/AndroidDumpsCI/.github/workflows/working/
              tar c /home/runner/work/AndroidDumpsCI/AndroidDumpsCI/.github/workflows/working/* | nice -n19 xz -9 -T4 > dump.tar.xz

       - name: Store Generated Files
         uses: actions/upload-artifact@v2
         with:
           path: /home/runner/work/AndroidDumpsCI/AndroidDumpsCI/.github/workflows/working/dump.tar.xz
           if-no-files-found: error