name: Dump
 
on:
  push:
    branches: [ main ]

env:
  ROM_URL: https://bigota.d.miui.com/V12.0.2.0.QFGINXM/miui_LAVENDERINGlobal_V12.0.2.0.QFGINXM_ef84abc890_10.0.zip
  TZ: America/Sao_Paulo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkouts
         uses: actions/checkout@master

       - name: Setup Dump Environment
         run: |
              sudo apt install unace unrar zip unzip p7zip-full p7zip-rar sharutils rar uudeview mpack arj cabextract file-roller device-tree-compiler liblzma-dev python3-pip python3-setuptools brotli liblz4-tool axel gawk aria2 detox cpio rename
              pip3 install pip setuptools wheel -U
              pip3 install backports.lzma protobuf pycrypto docopt zstandard twrpdtgen

       - name: Running Dumpyara Shell Script
         run: |
              bash .github/workflows/dumpyara.sh "$ROM_URL"

       - name: Checking Folder
         run: |
              cd /home/runner/work/AndroidDumpsCI/AndroidDumpsCI/.github/workflows/working/
              ls -la

       - name: Store Generated Files
         uses: actions/upload-artifact@v1
         with:
           name: Dump
           path: /home/runner/work/AndroidDumpsCI/AndroidDumpsCI/.github/workflows/working/*tar.xz
