name: Phoenix Firmware Dumper
 
on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: "Direct Link of the ROM/Firmware to Dump"
        required: true
      EXTRA_CMD:
        description: "Any Extra Command to Run Before Dump"
        required: false

defaults:
  run:
    shell: bash

env:
  ROM_URL: ${{ github.event.inputs.ROM_URL }}
  EXTRA_CMD: ${{ github.event.inputs.EXTRA_CMD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkouts
         uses: actions/checkout@v2

       - name: Clone Phoenix Firmware Dumper
         run: |
              git clone https://github.com/DroidDumps/phoenix_firmware_dumper.git

       - name: Setup Phoenix Dumper environment
         working-directory: phoenix_firmware_dumper
         run: |
              sudo bash setup.sh
              git config --global user.name "Sushrut1101"
              git config --global user.email "guptasushrut@gmail.com"

       - name: Setup Config envs
         working-directory: phoenix_firmware_dumper
         run: |
              echo "${{ secrets.GIT_TOKEN }}" > .github_token
              echo "${{ secrets.GIT_ORG_NAME }}" > .github_orgname
              echo "${{ secrets.BOT_TOKEN }}" > .tg_token
              echo "${{ secrets.CHAT_ID }}" > .tg_chat

       - name: Run the Extra Command
         working-directory: phoenix_firmware_dumper
         run: |
              $EXTRA_CMD

       - name: Start Dumping
         working-directory: phoenix_firmware_dumper
         run: |
              ./dumper.sh "$ROM_URL"
